### ISSUE TITLE
Typo in Overriding System.Object.Equals()

### ISSUE THREAD

**Issue by pmarangoni** [Apress/pro-c-sharp-8-w-.net-core-3#3]
In the paragraph at the top of page 252, it says the following:

> Even better, you no longer need to perform a property-by-property equality check, as you are **_not_** simply testing the value returned from `ToString()`.

I think it should be:
> Even better, you no longer need to perform a property-by-property equality check, as you are **_now_** simply testing the value returned from `ToString()`.

**Comment by skimedic** [comment]
Thank you! I've updated the text for the next edition.
