### ISSUE TITLE
Ch21 AutoLot.DAL -> bulkcopy appears to be transposing make and color

### ISSUE THREAD

**Issue by rodgerWithAD** [Apress/pro-c-sharp-8-w-.net-core-3#4]
steps to reproduce
1) build database in docker using bak file
2) download ch 21 code and build DAL and Client
3) run in debug, watching locals everything looks fine through line 83's ProcessBulkImport.ExecuteBulkImport(cars, "Inventory") but output after reading from database (line 85s var list = dal.GetAllInventory() in program.cs) shows that color and make are transposed on the bulkcopy. Select top 1000 in ssms/azure confirms that they are backwards in the DB.
4) confirmed with a fresh build of database on a second system

CarId   Make    Color   Pet Name
1       VW      Black   Zippy
2       Ford    Rust    Rusty
3       Saab    Black   Mel
4       Yugo    Yellow  Clunker
6       BMW     Green   Hank
7       BMW     Pink    Pinky
10      Blue    Honda   MyCar1
11      Red     Volvo   MyCar2
12      White   VW      MyCar3
13      Yellow  Toyota  MyCar4

**Comment by skimedic** [comment]
This has been fixed in the C# 9 book (and beyond). For the C# edition, make sure the property order in the Car entity and the 
 column order in the table match. I will update the errata.

**Comment by skimedic** [comment]
Errata has been updated.

**Comment by rodgerWithAD** [comment]
Awesome, thanks!
